CREATE USER 'repl_1'@'%' IDENTIFIED BY 'pass';
GRANT REPLICATION SLAVE ON *.* TO 'repl_1'@'%';
CHANGE REPLICATION SOURCE TO
  SOURCE_HOST='master-2',
  SOURCE_USER='repl_2',
  SOURCE_PASSWORD='pass',
  SOURCE_SSL=1;
START REPLICA;